version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "bharath-srinivas"
    reviewers:
      - "bharath-srinivas"
    pull-request-branch-name:
      separator: "-"
